steps:
  - name: "gcr.io/cloud-builders/go"
    args: ["install", "github.com/suchitpuri/gcp-cd-codelab"]
    env: ["PROJECT_ROOT=github.com/suchitpuri/gcp-cd-codelab"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/pso-suchit/gcp-cd-codelab:$COMMIT_SHA", "-f", "Dockerfile", "."]
images:
  - "gcr.io/pso-suchit/gcp-cd-codelab:$COMMIT_SHA"
